default_language_version:
    python: python3.11
default_stages:
    [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        name: Check trailing whitespace
        stages: [commit]
    -   id: end-of-file-fixer
        name: Check files end in a newline and only a newline
        stages: [commit]
-   repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
    -   id: black
        name: Formatter
        args: [--config, ./pyproject.toml]
        additional_dependencies:
        -   toml
        stages: [commit]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
    -   id: ruff
        name: Linter
        args: [--config, ./pyproject.toml]
        additional_dependencies:
          - toml
        stages: [commit]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        name: Type checker
        args: [--config-file, ./pyproject.toml]
        exclude: tests/
        additional_dependencies:
        -   toml
        -   types-requests
        -   pandas-stubs
        stages: [commit]
-   repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check
        name: Check pyproject.toml
        stages: [commit]
      - id: poetry-lock
        name: Check poetry.lock
        args: [--check, --no-update]
        stages: [commit]
